// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlankArticle: typeof import('./../src/components/BlankArticle.vue')['default']
    Edit: typeof import('./../src/views/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    Home: typeof import('./../src/views/Home.vue')['default']
    InputDialog: typeof import('./../src/components/InputDialog.vue')['default']
    Loading: typeof import('./../src/components/Loading.vue')['default']
    Login: typeof import('./../src/views/Login.vue')['default']
    Menu: typeof import('./../src/components/Menu.vue')['default']
    MyArticle: typeof import('./../src/components/MyArticle.vue')['default']
    MyAside: typeof import('./../src/components/MyAside.vue')['default']
  }
}

export { }
